### ISSUE TITLE
Download Manager?

### ISSUE THREAD

**Issue by steckerhalter** [skeeto/youtube-dl-emacs#1]
This looks like a decent download manager. Could it be split up into a generic download manager and a Youtube package that hooks into the generic download manager? I was thinking about writing one myself but this looks pretty good.

**Comment by skeeto** [comment]
You're right, this _could_ serve as the foundation for a general file 
download manager, with youtube-dl as just one of several external tools 
it supports (in addition to curl, wget, etc.). However, I personally 
only care about managing YouTube downloads.

**Comment by steckerhalter** [comment]
Let me know if you plan to split. Closing... thanks.

**Comment by stardiviner** [comment]
Do you accept PR to make this more general for other websites?

**Comment by skeeto** [comment]
Eh... I'm reluctant to extend this beyond its original, core purpose. I 
like having downloads oriented around YouTube IDs, and a more general 
download manager couldn't do this. What did you specifically have in 
mind?

**Comment by stardiviner** [comment]
I make a little modification. Check out this diff:
https://github.com/stardiviner/youtube-dl-emacs/compare/master...feature/remove-limitation

**Comment by steckerhalter** [comment]
@skeeto what I meant was having a generic dl manager (library?) that can be extended with plugins. so the youtube plugin would work with ids etc.
