### ISSUE TITLE
interprogram-paste-function can be nil

### ISSUE THREAD

**Issue by DamienCassou** [skeeto/youtube-dl-emacs#2]
In Emacs simple.el file, the use of `interprogram-paste-function` is always protected against `nil` values. Even though `nil` is not advertised as a valid value for the variable, you might want to do the same.

**Comment by basil-conto** [comment]
> `nil` is not advertised as a valid value for the variable

FWIW, it is under [`(elisp) Low-Level Kill Ring`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Low_002dLevel-Kill-Ring.html#index-interprogram_002dpaste_002dfunction-3271):

    Its value should be ‘nil’ or a function of no arguments.

**Comment by skeeto** [comment]
Fixed, thanks! I didn't know it could be nil.

**Comment by basil-conto** [comment]
Looks like there's one more call site in `youtube-dl-playlist`: https://github.com/skeeto/youtube-dl-emacs/blob/54d5a467af9116477e81be0b489a0d6480809a5f/youtube-dl.el#L312.

**Comment by skeeto** [comment]
Oops, thanks!
